version: "3"

vars:
  DAY:
    sh: date +%d
  TESTFILE: "test.txt"
  INPUTFILE: "input.txt"

tasks:
  init:
    cmds:
      - go run prep/main.go
      - open https://adventofcode.com/2024/day/{{.DAY}}

  test1:
    env:
      DEBUG: "1"
    cmds:
      - go run {{.DAY}}/main.go 1 {{.DAY}}/{{.TESTFILE}}

  test2:
    env:
      DEBUG: "1"
    cmds:
      - go run {{.DAY}}/main.go 2 {{.DAY}}/{{.TESTFILE}}

  run1:
    cmds:
      - go run {{.DAY}}/main.go 1 {{.DAY}}/{{.INPUTFILE}}

  run2:
    cmds:
      - go run {{.DAY}}/main.go 2 {{.DAY}}/{{.INPUTFILE}}
